SIMBOLOS_ARITIMETICOS=["*","/","+","-","^"]
SIMBOLOS_CONTENCAO=["(",")"]
SIMBOLOS_STRINGS={
    "'":"'",
    "\"":"\""
}
SIMBOLOS_SERIES_TEMPORAIS={
    "[":"]"
}
SIMBOLOS_NUMERICOS=["1","2","3","4","5","6","7","8","9","0","."]
SIMBOLOS_FUNCOES=["mediana","media","moda","desvio_padrao","variancia","plot_serie"]
SIMBOLOS_SEPARACAO=[","]